config/routes.rb
Gracie::Application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path
  get "words" => "pages#word_counter" # creates about_path
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def word_counter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="mastfoot">
	<div class="inner">
		<% if user_signed_in? %>
		    <p>
		    	<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
		    </p>
		<% else %>
			  <p>
			  	<%= link_to "Log in", new_user_session_path %>
			  	<%= link_to "Sign up", new_user_registration_path %>  	
			  </p> 
		<% end %>	  
		<p>
			Created by <%= link_to "@suchthekaitlin", "https://twitter.com/suchthekaitlin" %>
		</p>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="masthead clearfix">
	<div class="inner">
		<h3 class="masthead-brand">Gracie</h3>
	    <ul class="nav masthead-nav">
	        <li class="active"><%= link_to "Home", root_path %></li>
	        <li><%= link_to "About", about_path %></li>
	        <li><%= link_to "Word Counter", words_path %></li>
	        <li><a href="#">Other</a></li>
	    </ul>
 	</div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gracie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="site-wrapper layout">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <%= render "layouts/header" %>

          <% flash.each do |name, msg| %>
          	<%= content_tag(:div, msg, class: "alert alert-info") %>
          <% end %>          

          <%= yield %>

          <%= render "layouts/footer" %>

        </div>

      </div>

    </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About this site</h1>
<p>There's still a lot to be done here. Please come back soon.<p>

app/views/pages/home.html.erb
          <div class="inner cover">
            <h1 class="cover-heading">Gracie Carpenter</h1>
            <p class="lead">This is Dobby. He probably looks guilty because he recently tried to sneak into the refrigerator.</p>
          <% if user_signed_in? %>
            <p class="lead">
            <%= link_to "Get Started!", about_path, class: "btn btn-lg btn-default" %>
            </p>
          <% else %>
            <p class="lead">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-lg btn-default" %>
            </p>
          <% end %>
          </div>

app/views/pages/word_counter.html.erb
<div class="word-counter">
  <div class="row">
    <div class="col-sm-6">
      <h1>Word Counter</h1>
    </div>
    <div class="col-sm-6">
      <h1 class="count-label"></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <textarea rows="20"></textarea>
    </div>
  </div>
</div>

<script type="text/javascript">
  
  $(document).ready(function() {
    function countWordsInTextarea() {
      var text = $("textarea").val();
      text = text.replace(/(^\s*)|(\s*$)/gi,"");
      text = text.replace(/[ ]{2,}/gi," ");
      text = text.replace(/\n /,"\n");
      return text.split(' ').length;
    };

    $("textarea").on('input propertychange', function(){
      $(".count-label").html(countWordsInTextarea()); 
    }); 
  });
</script>